alertmanager_platform: linux-amd64
alertmanager_version: 0.26.0
alertmanager_name: "alertmanager-{{ alertmanager_version }}.{{ alertmanager_platform }}"
alertmanager_artifact: "{{ alertmanager_name }}.tar.gz"
